# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-10 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def get_default():
    try:
        from dashboard.models import System
        return System.objects.first().pk
    except:
        return None


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_system_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='system',
            field=models.ForeignKey(default=get_default(), on_delete=django.db.models.deletion.CASCADE, to='dashboard.System'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='ordernr',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('system', 'ordernr')]),
        ),
    ]
