# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_simplify_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[a-z0-9]+(_[a-z]+)?', flags=2)])),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('field', 'value'),
            },
        ),
        migrations.AlterField(
            model_name='system',
            name='hostname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='filter',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.System'),
        ),
    ]
