# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='refresh_interval',
            field=models.TextField(null=True),
        ),
    ]
