# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_cell_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache', models.TextField(null=True)),
                ('cache_tag', models.TextField(max_length=36, null=True)),
                ('cache_timestamp', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('cache_mimetype', models.TextField(null=True)),
                ('cache_uuid', models.TextField(null=True)),
                ('refresh_interval', models.TextField(null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page')),
            ],
            options={
                'db_table': 'query_cache',
            },
        ),
        migrations.RemoveField(
            model_name='query',
            name='cache',
        ),
        migrations.RemoveField(
            model_name='query',
            name='cache_mimetype',
        ),
        migrations.RemoveField(
            model_name='query',
            name='cache_timestamp',
        ),
        migrations.RemoveField(
            model_name='query',
            name='cache_uuid',
        ),
        migrations.AddField(
            model_name='querycache',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Query'),
        ),
        migrations.AlterUniqueTogether(
            name='querycache',
            unique_together=set([('query', 'page')]),
        ),
    ]
