# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_query_amcat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='amcat_query_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together=set([('system', 'amcat_query_id')]),
        ),
        migrations.AlterModelTable(
            name='querycache',
            table=None,
        ),
    ]
