# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20180702_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
