# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-26 18:26
from __future__ import unicode_literals

import dashboard.util.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_cell_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='highchartstheme',
            name='y_axis_has_line_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='highchartstheme',
            name='y_axis_line_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highchartstheme',
            name='y_label_has_line_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cell',
            name='customize',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, validators=[dashboard.util.validators.HighchartsCustomizationValidator((('yAxis.0.title.text', (str, 'text', 'y-Axis label', None, '<automatic>')), ('yAxis.1.title.text', (str, 'text', 'secondary y-Axis label', None, '<automatic>')), ('series.0.tooltip.valueDecimals', (int, 'number', 'Tooltip decimals', None, '<automatic>')), ('series.1.tooltip.valueDecimals', (int, 'number', 'Secondary tooltip decimals', None, '<automatic>')), ('legend.enabled', (bool, 'checkbox', 'Enable legend', True, 'true')), ('series.0.name', (str, 'text', 'Series name', None, '<automatic>')), ('series.1.name', (str, 'text', 'Secondary series name', None, '<automatic>')), ('credits.enabled', (bool, 'checkbox', 'Credits enabled', False, 'false')), ('credits.text', (str, 'text', 'Credits text', None, 'e.g. Highcharts.com')), ('credits.href', (str, 'text', 'Credits url', None, 'e.g. http://www.highcharts.com'))))]),
        ),
    ]
