# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-28 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20181226_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='hide_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='querycache',
            name='cache_uuid',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
