# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_hide menu option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='hide_menu',
            field=models.BooleanField(default=False, help_text='Hide left hand menu for non super user'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([]),
        ),
    ]
