# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_remove_unique_ordernr'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='page_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Page'),
        ),
    ]
