# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-02 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_add page_link tot specific cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='page_link',
        ),
        migrations.AddField(
            model_name='cell',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
