# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-29 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20200202_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='amcat_archived',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
